import { useEffect, useReducer, useState } from "react";
import { ArrowRight, CheckCircle, Clock, EnvelopeSimple, InstagramLogo, List, MapPin, Minus, Phone, Plus, ShoppingBag, Star, Trash, WarningCircle, WhatsappLogo, X } from "@phosphor-icons/react";
import { cartReducer, cartSubtotal, formatMoney, initialCart, lineTotal } from "./lib/cart";
import { fetchPublicBootstrap, placeOrder } from "./lib/api";
import businessConfig from "../../shared/businessConfig.json";
import AdminApp from "./admin/AdminApp";

const images = {
  hero: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1782005862/amas-kitchen/pexels-ekrulila-20488746_kz18zy.jpg",
  story: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1782005864/amas-kitchen/pexels-thomas-wilson-1334312084-30746554_y0jcan.jpg",
  gallery1: "https://images.pexels.com/photos/13915043/pexels-photo-13915043.jpeg?auto=compress&cs=tinysrgb&w=900",
  gallery2: "https://images.pexels.com/photos/20488744/pexels-photo-20488744.jpeg?auto=compress&cs=tinysrgb&w=900",
  gallery3: "https://images.pexels.com/photos/1813503/pexels-photo-1813503.jpeg?auto=compress&cs=tinysrgb&w=900",
  gallery4: "https://images.pexels.com/photos/5908228/pexels-photo-5908228.jpeg?auto=compress&cs=tinysrgb&w=900",
  gallery5: "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=900",
};

const navLinks = [{ label: "Home", href: "/" }, { label: "Menu", href: "/menu" }, { label: "Services", href: "/services" }, { label: "About", href: "/about" }, { label: "Contact", href: "/contact" }];
const services = ["Event Catering", "Corporate Lunches", "Private Dining", "Meal Plans", "Bulk Orders"];
const testimonials = [
  { name: "Naa Adoley", quote: "The jollof tasted like Sunday at home, but the presentation felt special." },
  { name: "Kojo Mensah", quote: "Our office lunch arrived warm, tidy and full of proper Ghanaian flavour." },
  { name: "Esi Ofori", quote: "Ama's Kitchen has become our reliable choice for family celebrations." },
];
const fallbackMenu = [
  { _id: "featured-jollof", name: "Smoky Jollof Rice", description: "Party-style rice, slow tomato stew, warm spice and grilled chicken.", basePrice: 9500, category: "Rice", available: true, images: [images.gallery2], addonGroups: [] },
  { _id: "featured-waakye", name: "Classic Waakye", description: "Rice and beans with shito, gari, kelewele and a soft egg.", basePrice: 10500, category: "Rice", available: true, images: [images.gallery1], addonGroups: [] },
  { _id: "featured-grill", name: "Charcoal Chicken", description: "Herb-marinated grilled chicken with fresh pepper sauce.", basePrice: 12000, category: "Grills", available: true, images: [images.story], addonGroups: [] },
];

function navigate(path) { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); window.scrollTo({ top: 0, behavior: "smooth" }); }
function Link({ href, className = "", children, onClick }) { return <a className={className} href={href} onClick={(event) => { event.preventDefault(); onClick?.(); navigate(href); }}>{children}</a>; }
function Stars() { return <span className="stars" aria-label="5 star rating">{[0, 1, 2, 3, 4].map((star) => <Star key={star} size={14} weight="fill" />)}</span>; }

function Navbar({ cartCount, onCart }) {
  const [open, setOpen] = useState(false);
  return <header className="site-nav"><Link href="/" className="brand">Ama’s <span>Kitchen</span></Link><nav className="desktop-nav">{navLinks.map((link) => <Link key={link.href} href={link.href}>{link.label}</Link>)}</nav><div className="nav-actions"><button className="cart-chip" onClick={onCart} aria-label="Open cart"><ShoppingBag size={18} />{cartCount}</button><Link href="/menu" className="order-link">Order Now</Link><button className="mobile-menu-button" onClick={() => setOpen(true)} aria-label="Open menu"><List size={24} /></button></div>{open && <div className="mobile-nav-panel"><button aria-label="Close menu" onClick={() => setOpen(false)}><X size={22} /></button>{navLinks.map((link) => <Link key={link.href} href={link.href} onClick={() => setOpen(false)}>{link.label}</Link>)}<Link href="/menu" className="order-link" onClick={() => setOpen(false)}>Order Now</Link></div>}</header>;
}

function Footer({ business, supportPhone }) { return <footer className="footer"><div><Link href="/" className="brand">Ama’s <span>Kitchen</span></Link><p>Authentic Ghanaian food, made with the warmth of home and delivered across {business.city}.</p></div><div><h3>Quick links</h3>{navLinks.map((link) => <Link key={link.href} href={link.href}>{link.label}</Link>)}</div><div><h3>Contact</h3><a href={`tel:${supportPhone || business.supportPhone}`}>{supportPhone || business.supportPhone}</a><a href={`mailto:${business.supportEmail}`}>{business.supportEmail}</a><span>{business.area}, {business.city}</span></div><div><h3>Opening hours</h3><p>{business.businessHours}</p><span>Instagram</span><span>WhatsApp</span></div></footer>; }

function HomePage({ menu }) {
  const featured = (menu?.length ? menu : fallbackMenu).slice(0, 3);
  return <><section className="home-hero"><div className="hero-copy"><p className="eyebrow">Premium Ghanaian kitchen</p><h1>Authentic Ghanaian food, made with the warmth of home.</h1><p>Freshly prepared and delivered across Accra.</p><div className="hero-actions"><Link href="/menu" className="primary-button">Order Now <ArrowRight size={18} /></Link><Link href="/menu" className="secondary-button">Explore Menu</Link></div></div><div className="hero-image"><img src={images.hero} alt="A premium Ghanaian meal from Ama's Kitchen" /><span>Small-batch cooking, generous flavour.</span></div></section><section className="section"><div className="section-heading"><p className="eyebrow">Signature dishes</p><h2>Three plates people come back for.</h2><Link href="/menu">View Full Menu <ArrowRight size={16} /></Link></div><div className="signature-grid">{featured.map((item) => <article className="premium-card" key={item._id}><img src={item.images?.[0] || images.gallery1} alt={item.name} /><div><h3>{item.name}</h3><p>{item.description}</p><b>{formatMoney(item.basePrice)}</b></div></article>)}</div></section><section className="split-section"><img src={images.story} alt="Ama's Kitchen food preparation" /><div><p className="eyebrow">Our story</p><h2>Food that feels cared for.</h2><p>Ama's Kitchen brings the comfort of Ghanaian home cooking into a polished daily dining experience. We cook fresh, layer flavour patiently and keep every order personal.</p><Link href="/about" className="text-link">Meet Ama's Kitchen</Link></div></section><GallerySection /><section className="section"><div className="section-heading"><p className="eyebrow">Services</p><h2>For lunches, gatherings and special tables.</h2><Link href="/services">Explore Services <ArrowRight size={16} /></Link></div><div className="service-strip">{services.map((service) => <article key={service}><h3>{service}</h3><p>Custom Ghanaian food support for moments that need more than the standard menu.</p></article>)}</div></section><section className="section testimonials"><p className="eyebrow">Kind words</p><div>{testimonials.map((item) => <article key={item.name}><Stars /><p>“{item.quote}”</p><b>{item.name}</b></article>)}</div></section><section className="final-cta"><p className="eyebrow">Ready to order?</p><h2>Choose your meal while the kitchen is open.</h2><Link href="/menu" className="primary-button">View Menu <ArrowRight size={18} /></Link></section></>;
}
function GallerySection() { return <section className="gallery-section" aria-label="Food gallery">{[images.gallery1, images.gallery2, images.gallery3, images.gallery4, images.gallery5].map((src, index) => <img key={src} src={src} alt={`Ama's Kitchen gallery dish ${index + 1}`} />)}</section>; }

function CategoryPills({ categories, active, setActive }) { return <div className="category-pills">{categories.map((category) => <button key={category} className={active === category ? "active" : ""} onClick={() => setActive(category)}>{category}</button>)}</div>; }
function FoodCard({ item, canOrder, onAdd }) { const [quantity, setQuantity] = useState(1); return <article className="menu-card"><img src={item.images?.[0] || images.gallery1} alt={item.name} /><div><span>{item.category}</span><h3>{item.name}</h3><p>{item.description}</p><b>{formatMoney(item.basePrice)}</b></div><div className="menu-card-actions"><div className="quantity"><button aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={14} /></button><span>{quantity}</span><button aria-label="Increase quantity" onClick={() => setQuantity(quantity + 1)}><Plus size={14} /></button></div><button disabled={!canOrder || !item.available} onClick={() => onAdd(item, quantity)}>Add</button></div></article>; }
function MenuPage({ bootstrap, error, cart, dispatch, openCart }) {
  const menu = bootstrap?.menu || [];
  const categoryBase = ["All", "Rice", "Grills", "Pasta", "Drinks", "Specials"];
  const availableCategories = categoryBase.filter((cat) => cat === "All" || menu.some((item) => item.category?.toLowerCase().includes(cat.toLowerCase().replace("s", ""))));
  const categories = availableCategories.length > 1 ? availableCategories : ["All", ...new Set(menu.map((item) => item.category))];
  const [active, setActive] = useState("All");
  const filtered = active === "All" ? menu : menu.filter((item) => item.category?.toLowerCase().includes(active.toLowerCase().replace("s", "")) || item.category === active);
  return <><section className="page-hero compact"><p className="eyebrow">Ordering menu</p><h1>Choose your plate.</h1><p>Browse the current kitchen menu, add your dishes and check out when ready.</p></section>{bootstrap && !bootstrap.ordering.canOrder && <div className="closure" role="status"><WarningCircle size={20} /><div><strong>Ordering is closed</strong><span>{bootstrap.ordering.reason} The menu is still open for browsing.</span></div></div>}<CategoryPills categories={categories} active={active} setActive={setActive} />{error ? <ErrorState message={error} /> : !bootstrap ? <SkeletonMenu /> : <section className="food-grid">{filtered.map((item) => <FoodCard key={item._id} item={item} canOrder={bootstrap.ordering.canOrder} onAdd={(selectedItem, quantity) => { dispatch({ type: "add", item: selectedItem, quantity, addons: [] }); openCart(); }} />)}</section>}<FloatingCartButton cart={cart} deliveryFee={bootstrap?.deliveryFee || 0} onClick={openCart} /></>;
}
function SkeletonMenu() { return <section className="food-grid">{[1, 2, 3, 4].map((item) => <div className="menu-skeleton" key={item} />)}</section>; }
function ErrorState({ message }) { return <div className="error-state" role="alert"><WarningCircle size={28} /><h2>The menu could not load.</h2><p>{message}</p><button onClick={() => location.reload()}>Try again</button></div>; }
function FloatingCartButton({ cart, deliveryFee, onClick }) { if (!cart.lines.length) return null; return <button className="floating-cart" onClick={onClick}>Cart ({cart.lines.length}) • {formatMoney(cartSubtotal(cart) + deliveryFee)}</button>; }

function CartDrawer({ open, onClose, cart, dispatch, deliveryFee }) { const subtotal = cartSubtotal(cart); return <div className={`drawer-shell ${open ? "open" : ""}`} aria-hidden={!open}><button className="drawer-backdrop" onClick={onClose} aria-label="Close cart" /><aside className="cart-drawer"><div className="drawer-heading"><div><p className="eyebrow">Cart</p><h2>Your order</h2></div><button onClick={onClose} aria-label="Close cart"><X size={20} /></button></div>{!cart.lines.length ? <div className="empty-cart"><ShoppingBag size={32} /><p>Your cart is empty.</p><span>Add something from the menu to begin.</span></div> : <div className="cart-lines">{cart.lines.map((line) => <div className="cart-line" key={line.lineId}><div><strong>{line.item.name}</strong><small>{formatMoney(lineTotal(line))}</small></div><div className="quantity"><button aria-label={`Decrease ${line.item.name}`} onClick={() => dispatch({ type: "quantity", lineId: line.lineId, quantity: line.quantity - 1 })}><Minus size={13} /></button><span>{line.quantity}</span><button aria-label={`Increase ${line.item.name}`} onClick={() => dispatch({ type: "quantity", lineId: line.lineId, quantity: line.quantity + 1 })}><Plus size={13} /></button></div><button aria-label={`Remove ${line.item.name}`} onClick={() => dispatch({ type: "remove", lineId: line.lineId })}><Trash size={17} /></button></div>)}</div>}<dl className="totals"><div><dt>Subtotal</dt><dd>{formatMoney(subtotal)}</dd></div><div><dt>Delivery</dt><dd>{formatMoney(deliveryFee)}</dd></div><div><dt>Total</dt><dd>{formatMoney(subtotal + deliveryFee)}</dd></div></dl><Link href="/checkout" className={`checkout-link ${!cart.lines.length ? "disabled" : ""}`} onClick={onClose}>Checkout</Link></aside></div>; }

function CheckoutPage({ bootstrap, cart, dispatch, onSuccess }) { const business = bootstrap?.business || businessConfig; const [form, setForm] = useState({ customerName: "", phone: "", email: "", line1: "", line2: "", city: business.city, deliveryArea: "", instructions: "", notes: "", paymentMethod: "Cash on Delivery" }); const [state, setState] = useState({ status: "idle", message: "" }); const subtotal = cartSubtotal(cart); const deliveryFee = bootstrap?.deliveryFee || 0; const eligible = cart.lines.length > 0 && (!bootstrap || bootstrap.ordering.canOrder) && subtotal >= (bootstrap?.minimumOrder || 0); const update = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value })); async function submit(event) { event.preventDefault(); if (!eligible) return; setState({ status: "submitting", message: "" }); try { const order = await placeOrder({ customerName: form.customerName, phone: form.phone, email: form.email, items: cart.lines.map((line) => ({ foodItemId: line.item._id, quantity: line.quantity, selectedAddonIds: line.addons.map((addon) => addon.id || addon._id) })), deliveryAddress: { line1: form.line1, line2: form.line2, city: form.city, instructions: form.instructions }, deliveryArea: form.deliveryArea, notes: form.notes }); onSuccess(order); dispatch({ type: "clear" }); navigate("/order-confirmation"); } catch (error) { setState({ status: "error", message: error.message }); } }
  return <section className="checkout-page"><div><p className="eyebrow">Checkout</p><h1>Complete your order.</h1><div className="summary-box"><h2>Order summary</h2>{cart.lines.length === 0 ? <p>Your cart is empty.</p> : cart.lines.map((line) => <p key={line.lineId}><span>{line.quantity} × {line.item.name}</span><b>{formatMoney(lineTotal(line))}</b></p>)}<dl className="totals"><div><dt>Subtotal</dt><dd>{formatMoney(subtotal)}</dd></div><div><dt>Delivery</dt><dd>{formatMoney(deliveryFee)}</dd></div><div><dt>Total</dt><dd>{formatMoney(subtotal + deliveryFee)}</dd></div></dl></div></div><form className="premium-form" onSubmit={submit}><Field label="Name" name="customerName" value={form.customerName} onChange={update} required /><Field label="Phone" name="phone" value={form.phone} onChange={update} required /><Field label="Email optional" name="email" type="email" value={form.email} onChange={update} /><Field label="Delivery address" name="line1" value={form.line1} onChange={update} required /><Field label="Notes optional" name="notes" as="textarea" value={form.notes} onChange={update} /><label className="field"><span>Delivery area</span><select name="deliveryArea" value={form.deliveryArea} onChange={update} required><option value="">Choose area</option>{(bootstrap?.deliveryZones || []).map((zone) => <option key={zone._id || zone.name}>{zone.name}</option>)}</select></label><label className="field"><span>Payment method</span><select name="paymentMethod" value={form.paymentMethod} onChange={update}><option>Cash on Delivery</option></select></label>{state.status === "error" && <p className="form-error" role="alert"><WarningCircle size={17} />{state.message}</p>}<button className="primary-button" disabled={!eligible || state.status === "submitting"}>{state.status === "submitting" ? "Placing order..." : "Place order"}</button></form></section>; }
function Field({ label, as, ...props }) { const Tag = as === "textarea" ? "textarea" : "input"; return <label className="field"><span>{label}</span><Tag {...props} /></label>; }
function ServicesPage() { return <><section className="page-hero"><p className="eyebrow">Services</p><h1>Ghanaian food for bigger moments.</h1><p>Tell us what you need and we will shape a custom quote for your guests, team or private table.</p></section><section className="service-grid">{services.map((service) => <article key={service}><h2>{service}</h2><p>Freshly prepared menus, clear portions and dependable delivery or setup.</p></article>)}</section><section className="split-section"><div><p className="eyebrow">How it works</p><ol className="steps"><li>Tell us what you need</li><li>Receive a custom quote</li><li>We prepare everything</li><li>Delivery or setup</li></ol></div><img src={images.gallery4} alt="Prepared food service spread" /></section><InquiryForm /></>; }
function InquiryForm() { return <section className="inquiry"><p className="eyebrow">Request a Quote</p><form className="premium-form"><Field label="Name" required /><Field label="Phone" required /><Field label="Email" type="email" /><Field label="Service needed" required /><Field label="Event date optional" type="date" /><Field label="Number of guests optional" type="number" /><Field label="Details" as="textarea" required /><button className="primary-button" type="button">Request a Quote</button></form></section>; }
function AboutPage() { return <><section className="page-hero"><p className="eyebrow">About</p><h1>Built on warmth, freshness and Ghanaian flavour.</h1><p>Ama's Kitchen is a delivery-first kitchen making everyday meals and special orders feel considered.</p></section><section className="split-section"><img src={images.story} alt="Ama's Kitchen brand story" /><div><h2>Our brand story</h2><p>We cook the food people miss: smoky rice, rich stews, careful grills and generous sides. The goal is simple food with a premium level of care.</p><h3>Mission</h3><p>Serve fresh Ghanaian food across Accra with consistency, comfort and dignity.</p></div></section><section className="service-strip values"><article><h3>Warmth</h3><p>Food should feel personal.</p></article><article><h3>Freshness</h3><p>Small batches protect flavour.</p></article><article><h3>Trust</h3><p>Clear ordering and dependable delivery.</p></article></section><GallerySection /><section className="final-cta"><h2>Ready for a plate?</h2><Link href="/menu" className="primary-button">Go to Menu</Link></section></>; }
function ContactPage({ business, supportPhone }) { return <><section className="page-hero compact"><p className="eyebrow">Contact</p><h1>Reach Ama's Kitchen.</h1><p>Questions, service requests and order support are all welcome.</p></section><section className="contact-grid"><a href={`tel:${supportPhone || business.supportPhone}`}><Phone />Phone<span>{supportPhone || business.supportPhone}</span></a><a href="https://wa.me/" target="_blank" rel="noreferrer"><WhatsappLogo />WhatsApp<span>Message us</span></a><a href="https://instagram.com/" target="_blank" rel="noreferrer"><InstagramLogo />Instagram<span>@amaskitchen</span></a><a href={`mailto:${business.supportEmail}`}><EnvelopeSimple />Email<span>{business.supportEmail}</span></a><article><Clock />Business hours<span>{business.businessHours}</span></article><article><MapPin />Location<span>{business.area}, {business.city}</span></article></section><section className="map-placeholder">Map placeholder for Ama's Kitchen delivery area</section><InquiryForm /></>; }
function ConfirmationPage({ order }) { return <section className="confirmation"><CheckCircle size={56} weight="fill" /><p className="eyebrow">Order received</p><h1>Thank you. We are preparing your food.</h1><p>{order?.orderNumber ? `Order reference: ${order.orderNumber}` : "Your order reference will appear once confirmed by the kitchen."}</p>{order && <div className="summary-box"><h2>Order summary</h2><p><span>Total</span><b>{formatMoney(order.total)}</b></p></div>}<p>Estimated delivery: freshly prepared for immediate dispatch across Accra.</p><div className="hero-actions"><Link href="/menu" className="primary-button">Back to Menu</Link><Link href="/" className="secondary-button">Home</Link></div></section>; }

function PublicApp() { const [path, setPath] = useState(window.location.pathname); const [bootstrap, setBootstrap] = useState(null); const [error, setError] = useState(""); const [cartOpen, setCartOpen] = useState(false); const [lastOrder, setLastOrder] = useState(null); const [cart, dispatch] = useReducer(cartReducer, initialCart, (value) => { try { return JSON.parse(localStorage.getItem("amas-cart")) || value; } catch { return value; } }); useEffect(() => { const update = () => setPath(window.location.pathname); window.addEventListener("popstate", update); return () => window.removeEventListener("popstate", update); }, []); useEffect(() => { localStorage.setItem("amas-cart", JSON.stringify(cart)); }, [cart]); useEffect(() => { const controller = new AbortController(); fetchPublicBootstrap({ signal: controller.signal }).then(setBootstrap).catch((reason) => { if (reason.name !== "AbortError") setError(reason.message); }); return () => controller.abort(); }, []); const business = bootstrap?.business || businessConfig; const supportPhone = bootstrap?.supportPhone || business.supportPhone; const deliveryFee = bootstrap?.deliveryFee || 0; const page = path === "/menu" ? <MenuPage bootstrap={bootstrap} error={error} cart={cart} dispatch={dispatch} openCart={() => setCartOpen(true)} /> : path === "/checkout" ? <CheckoutPage bootstrap={bootstrap} cart={cart} dispatch={dispatch} onSuccess={setLastOrder} /> : path === "/services" ? <ServicesPage /> : path === "/about" ? <AboutPage /> : path === "/contact" ? <ContactPage business={business} supportPhone={supportPhone} /> : path === "/order-confirmation" ? <ConfirmationPage order={lastOrder} /> : path === "/cart" ? <MenuPage bootstrap={bootstrap} error={error} cart={cart} dispatch={dispatch} openCart={() => setCartOpen(true)} /> : <HomePage menu={bootstrap?.menu} />; return <main><Navbar cartCount={cart.lines.length} onCart={() => setCartOpen(true)} />{page}<Footer business={business} supportPhone={supportPhone} /><CartDrawer open={cartOpen} onClose={() => setCartOpen(false)} cart={cart} dispatch={dispatch} deliveryFee={deliveryFee} /></main>; }
export default function App() { return window.location.pathname.startsWith("/admin") ? <AdminApp /> : <PublicApp />; }
